general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on
}

# Screen dim at 1 min
listener {
	timeout = 60
	on-timeout = brightnessctl --save && brightnessctl -e4 -n2 set 10%-
	on-resume = brightnessctl --restore
}

# Screen off at 5 minutes
listener {
	timeout = 300
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

# Lock at 5 minutes 30 seconds
listener {
	timeout = 330
	on-timeout = loginctl lock-session
}

# Suspend at 30 minutes
listener {
	timeout = 1800
	on-timeout = systemctl suspend
}
